const columns = [
  {
    title: '应用名称',
    dataIndex: 'name',
    key: 'name',
    fixed: 'left',
    width: '20%',
  },
  {
    title: 'SDK',
    dataIndex: 'sdk',
    key: 'sdk',
    width: '40px',
  },
  {
    title: '实时评分',
    dataIndex: 'score',
    key: 'score',
    width: '50px',
    align: 'center',
  },
  {
    title: 'PV量',
    dataIndex: 'pv',
    key: 'pv',
    width: '50px',
    align: 'center',
  },
  {
    title: 'UV量',
    key: 'uv',
    dataIndex: 'uv',
    width: '50px',
    align: 'center',
  },
  {
    title: '活跃趋势',
    key: 'chartOption',
    dataIndex: 'chartOption',
    width: '100px',
    align: 'center',
  },
  {
    title: '页面加载',
    key: 'pageloadData',
    dataIndex: 'pageloadData',
    width: '60px',
    align: 'center',
  },
  {
    title: '运行时异常',
    key: 'runtimeError',
    dataIndex: 'runtimeError',
    width: '65px',
    align: 'center',
  },
  {
    title: '资源异常',
    key: 'resourceError',
    dataIndex: 'error',
    width: '50px',
    align: 'center',
  },
  {
    title: '请求成功率',
    key: 'success',
    dataIndex: 'success',
    width: '65px',
    align: 'center',
  },
  {
    title: '看板',
    key: 'screen',
    dataIndex: 'screen',
    width: '160px',
    fixed: 'right',
    align: 'center',
  },
  {
    title: '操作',
    key: 'action',
    dataIndex: 'action',
    fixed: 'right',
    width: '50px',
    align: 'center',
  },
]

export default columns
