const columns = [
  {
    title: '应用名称',
    dataIndex: 'name',
    key: 'name',
    slots: { customRender: 'rendername' },
    fixed: 'left',
    width: '160px',
  },
  {
    title: 'SDK版本',
    dataIndex: 'sdk',
    key: 'sdk',
    slots: { customRender: 'sdk' },
    width: '35px',
  },
  {
    title: '实时评分',
    dataIndex: 'score',
    key: 'score',
    slots: { customRender: 'score' },
    width: '50px',
    align: 'center',
  },
  {
    title: 'PV量',
    dataIndex: 'pv',
    key: 'pv',
    slots: { customRender: 'pv' },
    width: '50px',
    align: 'center',
  },
  {
    title: 'UV量',
    key: 'uv',
    dataIndex: 'uv',
    slots: { customRender: 'uv' },
    width: '50px',
    align: 'center',
  },
  {
    title: '活跃趋势',
    key: 'chartOption',
    dataIndex: 'chartOption',
    slots: { customRender: 'chartOption' },
    width: '100px',
    align: 'center',
  },
  {
    title: '页面加载',
    key: 'pageloadData',
    dataIndex: 'pageloadData',
    slots: { customRender: 'pageloadData' },
    width: '60px',
    align: 'center',
  },
  {
    title: '运行时异常率',
    key: 'runtimeError',
    dataIndex: 'runtimeError',
    slots: { customRender: 'runtimeError' },
    width: '50px',
    align: 'center',
  },
  {
    title: '资源异常率',
    key: 'error',
    dataIndex: 'error',
    slots: { customRender: 'resourceError' },
    width: '50px',
    align: 'center',
  },
  {
    title: '请求成功率',
    key: 'success',
    dataIndex: 'success',
    slots: { customRender: 'success' },
    width: '50px',
    align: 'center',
  },
  // {
  //   title: '活跃趋势',
  //   key: 'chartOption',
  //   dataIndex: 'chartOption',
  //   slots: { customRender: 'chartOption' },
  //   width: '100px',
  //   align: 'center',
  // },
  {
    title: '看板',
    key: 'screen',
    dataIndex: 'screen',
    slots: { customRender: 'screen' },
    width: '150px',
    fixed: 'right',
    align: 'center',
  },
  {
    title: '操作',
    key: 'action',
    dataIndex: 'action',
    slots: { customRender: 'action' },
    fixed: 'right',
    width: '50px',
    align: 'center',
  },
];

export default columns;
